# Generated by Django 4.2.16 on 2024-10-02 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BussinessInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=100)),
                ('business_phone', models.CharField(max_length=12)),
                ('business_email', models.EmailField(max_length=254, unique=True)),
                ('business_website', models.URLField()),
                ('business_info', models.TextField(max_length=500)),
                ('business_location', models.CharField(max_length=100)),
                ('business_address', models.TextField(max_length=200)),
                ('gstin', models.CharField(max_length=12)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='agent',
            old_name='region',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='contact_info',
        ),
        migrations.AddField(
            model_name='agent',
            name='agent_email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='agent_phone',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='business_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='agent_module.bussinessinfo'),
        ),
    ]
