# Generated by Django 4.2.16 on 2024-10-02 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_module', '0002_student_lead_source'),
        ('application_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_10', models.DecimalField(decimal_places=1, max_digits=3)),
                ('std_12', models.DecimalField(decimal_places=1, max_digits=3)),
                ('bachelors', models.DecimalField(decimal_places=1, max_digits=3)),
                ('student_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academics', to='student_module.studentprofile')),
            ],
        ),
    ]
