# Generated by Django 4.2.16 on 2024-10-01 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setting_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.DateTimeField(auto_now=True)),
                ('countrylist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='University_list', to='setting_module.countrylist')),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme_name', models.CharField(default='Bachelor', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.DateTimeField(auto_now=True)),
                ('universitylist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programme_list', to='university_module.universitylist')),
            ],
        ),
    ]
