# Generated by Django 4.2.16 on 2024-10-02 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting_module', '0003_citylist_universitycampus'),
        ('university_module', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='universitylist',
            old_name='name',
            new_name='university_name',
        ),
        migrations.RemoveField(
            model_name='universitylist',
            name='countrylist',
        ),
        migrations.AddField(
            model_name='programmelist',
            name='programme_duration',
            field=models.CharField(default='2024-2025', max_length=20),
        ),
        migrations.AddField(
            model_name='universitylist',
            name='campuslist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='University_list', to='setting_module.universitycampus'),
        ),
        migrations.AddField(
            model_name='universitylist',
            name='qs_ranking',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='universitylist',
            name='university_logo',
            field=models.ImageField(null=True, upload_to='university_logo/'),
        ),
        migrations.AlterField(
            model_name='programmelist',
            name='universitylist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programme_list', to='university_module.universitylist'),
        ),
        migrations.CreateModel(
            name='CollageList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collage_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.DateTimeField(auto_now=True)),
                ('university_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collage_list', to='university_module.universitylist')),
            ],
        ),
        migrations.AddField(
            model_name='programmelist',
            name='collagelist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programme_list', to='university_module.collagelist'),
        ),
    ]
