# Generated by Django 4.2.16 on 2024-10-01 04:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(default='Middle Name', max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(default='Delhi', max_length=20)),
                ('state', models.CharField(default='Maharashtra', max_length=20)),
                ('country', models.CharField(default='India', max_length=20)),
                ('dob', models.DateField(default='2006-09-25')),
                ('gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female')], default='male', max_length=20)),
                ('marital_status', models.CharField(choices=[('Married', 'married'), ('Unmarried', 'unmarried')], default='unmarried', max_length=20)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentTempAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_1', models.CharField(max_length=200)),
                ('address_2', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(default='Delhi', max_length=20)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='India', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Student_Temp_Addresses', to='student_module.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_no', models.CharField(default='no_passport_no', max_length=20)),
                ('passport_issue_date', models.DateField()),
                ('passport_exp_date', models.DateField()),
                ('passport_issue_country', models.CharField(default='India', max_length=20)),
                ('city_of_birth', models.CharField(default='Delhi', max_length=20)),
                ('country_of_birth', models.CharField(default='India', max_length=20)),
                ('nationality', models.CharField(default='Indian', max_length=20)),
                ('citizenship', models.CharField(default='India', max_length=20)),
                ('citizenship_of_more_country', models.BooleanField(default=False)),
                ('living_in_any_other_company', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_profiles', to='student_module.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentPermanentAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_1', models.CharField(max_length=200)),
                ('address_2', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(default='Delhi', max_length=20)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='India', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Student_Permanent_Addresses', to='student_module.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_applied_immigration_for_any_country', models.BooleanField(default=False)),
                ('has_suffering_from_any_major_disease', models.BooleanField(default=False)),
                ('visa_has_refused_once', models.BooleanField(default=False)),
                ('has_convicted_in_a_criminal_case', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Student_backgrounds', to='student_module.student')),
            ],
        ),
        migrations.CreateModel(
            name='ImportantContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name', max_length=20)),
                ('phone_no', models.CharField(blank=True, max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('relation_with_the_applicant', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='important_contacts', to='student_module.student')),
            ],
        ),
    ]
