# Generated by Django 4.2.16 on 2024-10-02 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intakelist',
            name='intake_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
